config (auth.yml, config.yml) QOL additions
CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins pull request #16
Opened 2021-10-22 07:14 UTC by blakephillips

I added some things that would hopefully make the experience easier for some users not too familiar with setting up configuration values. 

Things I added: 

- On config file error, tell the user what they should do to fix error
- Ask user if they want help fixing the error, and if they do (and the example file exists) copy and rename the example file(s) to the proper name with the default variables.

2021-12-03 18:36 UTC, CyberPunkMetalHead commented
I like the idea of automatically creating a config.yml and prompting the user to fill in their details via the console. Has this been tested?

2021-12-03 20:13 UTC, blakephillips commented
> I like the idea of automatically creating a config.yml and prompting the user to fill in their details via the console. Has this been tested?

I tested this back in October, and it worked fine. Not sure about today, as I haven't been keeping up with the recent changes. It basically just adds a condition when checking for config yml files to ask the user if they want the app to copy / paste the .example.yml file for that particular config file and if they accept it just pastes and renames to remove the .example. from the name (if user says yes)

2021-12-28 18:46 UTC, Linus045 requested changes

2021-12-28 18:46 UTC, Linus045 commented on auth/gateio_auth.py
> +        raise FileNotFoundError("check that your "+file+" exists, use "+file.split(".")[0]+
You can replace `e: " + str(e)` with the following syntax:
```
raise FileNotFoundError(...) from e
```
which will re-raise the exception and append your text, see [here](https://stackoverflow.com/questions/6062576/adding-information-to-an-exception/6062799) for more info

2021-12-28 18:46 UTC, Linus045 commented on auth/gateio_auth.py
> +        raise FileNotFoundError("check that your "+file+" exists, use "+file.split(".")[0]+
Please utilize fstrings 
```suggestion
        raise FileNotFoundError(f"check that your {file} exists, use {file.split(".")[0]}.example.yml as a template.")
```

2021-12-28 18:46 UTC, Linus045 commented on load_config.py
> +            if config['TRADE_OPTIONS']['TEST']:
This does not belong here and should be moved outside, otherwise you will print the message every time someone loads the config

2021-12-28 18:46 UTC, Linus045 commented on load_config.py
> +        raise FileNotFoundError("check that your "+file_name+" exists, use "
utilize fstrings, similar to above

2021-12-28 18:46 UTC, Linus045 commented on load_config.py
> +    sys.exit()
Don't call `sys.exit()` here, you raise an exception after calling `create_config()` anyway, which will terminate the process.

2024-02-16 22:30 UTC, closed without merging